language: rust
sudo: false

rust:
  - stable
  - beta
  - nightly

script:
  - cargo test
  - cargo run -- --help

after_success:
  - curl https://learning-on-chip.github.io/travis/documentation.sh | bash

env:
  global:
    secure: HPB7F7C0/K9XkJL8DKAIMAsNbtGJETGG+JEezRHXgHj+D1GiGVqJ+3KieW3czqY4a6ecciW+8c89kWG5arcUc2AdKY9xMCYgkJ0B5BgIp4UMw6A5ILG7Tuez6uT/PS1Ta5RWDBrv9rABn29+Vmbj/1koeEsyYs0roHfEzUt/qHPW/Wi1NmPv3DNQJn/dejC2NQxEMwvKdXLH3k637hKONbNAxLeD7izirsM51hX6h7k+NPTj+86pO+KcvBH3oJ2ip8qhQPbJKH4FQ3p3cNBJ86qwmctRFMSQZ+3fnKeLld36Jr2TKT54obep67fziaeBqj8pk/vm3jI7ACIJK1zF7f1miVpYAwrSPk7AkXMyqnlFotIs/Cw0tdLPlZA5yiQCoXjLoJbLp35N+Rn/kxw1/imVM/7dLmWYUqWNmHSslkaBVsM0MAtfvSdhQ5aOE+o89fvUltFlqWHU3nl1F6ZKKjy8UiHJGTbdTpcHGzVifDh/3fZ5esS2ZoOhVfUvj/psOE7SvTqykyrNASSnnZctpPsgB+kjkTiaMEPP123kSlm+a1DyeEzPeGgd9G4UljJ2uYyEswfuSdKe/ktFAi0TNGhU9uV4MzSW/9HJnPIaoJfyn4UFxCfShr079ONy0TLEvK44slJ7Q8RkqqJQvELd6Aa6evP1x+hPqqNyLwZ+g7I=

notifications:
  email: false
