[package]
name = "squire"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]

[lib]
name = "squire"
path = "src/lib/squire.rs"

[[bin]]
name = "squire"
path = "src/bin/squire.rs"
doc = false

[dependencies]
arguments = "*"
hiredis = "*"
mcpat = { version = "*", features = ["caching"] }
sqlite = "*"
