[package]
name = "bullet"
version = "0.0.1"
authors = ["Ivan Ukhov <ivan.ukhov@gmail.com>"]

[lib]
name = "bullet"
path = "src/lib/bullet.rs"

[[bin]]
name = "bullet"
path = "src/bin/bullet.rs"
doc = false

[dependencies]
arguments = "*"
hiredis = "*"
mcpat = { version = "*", features = ["caching"] }
sqlite = "*"
